name: Test backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [14, 16]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
      - run: sudo add-apt-repository -y ppa:transmissionbt/ppa
      - run: sudo apt-get install -y qbittorrent-nox transmission-daemon

      - run: |
          wget https://github.com/jesec/rtorrent/releases/latest/download/rtorrent-linux-amd64.deb
          sudo dpkg -i rtorrent-linux-amd64.deb

      - run: npm ci
      - run: npm test || npm test || npm test

      - uses: codecov/codecov-action@v1
        if: matrix.node == 16

      - run: |
          sudo apt-get remove --purge -y rtorrent
          sudo apt-get install -y rtorrent

      - run: npm test -- --selectProjects rtorrent || npm test -- --selectProjects rtorrent || npm test -- --selectProjects rtorrent
        if: matrix['node'] == '16'
